CREATE TABLE [dbo].[Full Line List with Sls Forecast] (
    [Product_Minor]                          NVARCHAR (50)  NOT NULL,
    [Article_No]                             NVARCHAR (50)  NOT NULL,
    [Colours]                                NVARCHAR (50)  NOT NULL,
    [Style_Colour]                           NVARCHAR (50)  NOT NULL,
    [StyleColourNoSpace]                     NVARCHAR (50)  NOT NULL,
    [Style_Description]                      NVARCHAR (50)  NOT NULL,
    [Product]                                NVARCHAR (50)  NOT NULL,
    [Supplier]                               NVARCHAR (50)  NOT NULL,
    [COO]                                    NVARCHAR (50)  NOT NULL,
    [Core_Seasonal]                          NVARCHAR (50)  NOT NULL,
    [Drop_No]                                INT            NOT NULL,
    [Drop_Date]                              DATETIME2 (7)  NOT NULL,
    [Wholesale]                              NVARCHAR (50)  NOT NULL,
    [RRP_Price]                              NVARCHAR (50)  NOT NULL,
    [Landed_UK_price]                        NVARCHAR (50)  NOT NULL,
    [EURO_landed_price]                      NVARCHAR (50)  NOT NULL,
    [Margin]                                 NVARCHAR (50)  NOT NULL,
    [BULK_PRICE]                             NVARCHAR (50)  NOT NULL,
    [Sizes]                                  NVARCHAR (150) NULL,
    [Freight_Term]                           NVARCHAR (50)  NOT NULL,
    [Comments]                               NVARCHAR (100) NULL,
    [MOQ]                                    NVARCHAR (50)  NULL,
    [RAP_offered]                            NVARCHAR (50)  NULL,
    [RAP_to_in_DC]                           INT            NOT NULL,
    [Offered_in_DC]                          NVARCHAR (50)  NULL,
    [Variance_in_Days]                       INT            NOT NULL,
    [RAP_Required]                           DATETIME2 (7)  NOT NULL,
    [Round_2_Salesman_Forecast]              INT            NOT NULL,
    [Round_2_Salesman_Forecast_Style_Colour] NVARCHAR (50)  NOT NULL,
    [Comment]                                NVARCHAR (50)  NULL
);

