CREATE TABLE [dbo].[Glen_1] (
    [Company]               VARCHAR (2)     NOT NULL,
    [Invoice Number]        VARCHAR (7)     NOT NULL,
    [Invoice Period]        DECIMAL (5)     NOT NULL,
    [Period Year]           DECIMAL (4)     NOT NULL,
    [Period Month]          DECIMAL (2)     NOT NULL,
    [Period Date]           DATETIME        NULL,
    [VF Invoice Period]     DECIMAL (5)     NOT NULL,
    [VF Period Year]        DECIMAL (4)     NOT NULL,
    [VF Period Month]       DECIMAL (2)     NOT NULL,
    [VF Period Date]        DATETIME        NULL,
    [Invoice Type]          VARCHAR (2)     NOT NULL,
    [Order Type]            VARCHAR (30)    NOT NULL,
    [Invoice Date]          DATETIME        NULL,
    [Year of Invoice Date]  DECIMAL (4)     NOT NULL,
    [Month of Invoice Date] DECIMAL (2)     NOT NULL,
    [Day of Invoice Date]   DECIMAL (2)     NOT NULL,
    [Line Quantity]         DECIMAL (11, 3) NOT NULL,
    [Line Cost Base]        DECIMAL (15, 2) NOT NULL,
    [Line Value Base]       DECIMAL (15, 2) NOT NULL,
    [Line Value Prime]      DECIMAL (15, 2) NOT NULL,
    [Profit]                DECIMAL (15, 2) NOT NULL,
    [Line Vat Base]         DECIMAL (15, 2) NOT NULL,
    [Line Vat Prime]        DECIMAL (15, 2) NOT NULL,
    [Line Vat Code]         VARCHAR (3)     NOT NULL,
    [Currency Code]         VARCHAR (3)     NOT NULL,
    [Customer Key]          VARCHAR (13)    NOT NULL,
    [SKU Key]               VARCHAR (17)    NOT NULL,
    [Expr1]                 VARCHAR (13)    NULL,
    [Customer]              VARCHAR (8)     NOT NULL,
    [Delivery Sequence]     VARCHAR (3)     NOT NULL,
    [Customer Name]         VARCHAR (35)    NOT NULL,
    [Salesman Code]         VARCHAR (2)     NOT NULL,
    [Salesman Description]  VARCHAR (30)    NOT NULL,
    [Channel]               VARCHAR (30)    NOT NULL,
    [Corporation]           VARCHAR (8)     NOT NULL,
    [Corporation Name]      VARCHAR (35)    NOT NULL,
    [Customer Division]     VARCHAR (30)    NOT NULL,
    [Customer Sub Division] VARCHAR (30)    NOT NULL,
    [Customer Region]       VARCHAR (30)    NOT NULL,
    [Customer Territory]    VARCHAR (30)    NOT NULL,
    [Post Code]             VARCHAR (12)    NOT NULL,
    [Outcode]               VARCHAR (6)     NOT NULL,
    [Country Code]          VARCHAR (30)    NOT NULL,
    [Vat Country]           VARCHAR (3)     NOT NULL,
    [Vat Registration]      VARCHAR (20)    NOT NULL,
    [Expr2]                 VARCHAR (17)    NOT NULL,
    [SKU Code]              VARCHAR (15)    NOT NULL,
    [SKU Description]       VARCHAR (36)    NOT NULL,
    [Style]                 VARCHAR (9)     NOT NULL,
    [Style Description]     VARCHAR (18)    NOT NULL,
    [Colour]                VARCHAR (3)     NOT NULL,
    [Colour Description]    VARCHAR (13)    NOT NULL,
    [Size]                  VARCHAR (3)     NOT NULL,
    [Size Description]      VARCHAR (5)     NOT NULL,
    [Product Type]          VARCHAR (30)    NOT NULL,
    [Product Class]         VARCHAR (30)    NOT NULL,
    [Product Major]         VARCHAR (30)    NOT NULL,
    [Product Minor]         VARCHAR (30)    NOT NULL,
    [Product Country]       VARCHAR (30)    NOT NULL,
    [Division]              VARCHAR (30)    NOT NULL,
    [StyCol]                VARCHAR (8000)  NULL
);

